spring:
  config:
    activate:
      on-profile: dev
  datasource:
    initialization-mode: embedded
    platform: postgres
    username: SpringBootUser
    password: 123456
    url: jdbc:postgresql://localhost:5432/springboot
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  data:
    rest:
      basePath: /apix
logging:
  level:
    org:
      hibernate:
        engine:
        jdbc:
          env:
            internal:
              LobCreatorBuilderImpl: error
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug
  file:
    path: spring101/logs
    name: ${logging.file.path}/myapp.log
cthye:
  logging:
    logger-name: LinkedIn-Cthye
server:
  port: 8000
  ssl:
    key-store: spring101/src/main/resources/keystore.jks
    key-alias: spring101
    key-store-password: password
    key-store-type: JKS
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
security:
  jwt:
    token:
      secret-key: some-secret-key
      expiration: 600000
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        engine:
        jdbc:
          env:
            internal:
              LobCreatorBuilderImpl: error
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug

