CREATE TABLE ROOM
(
    ROOM_ID     SERIAL PRIMARY KEY,
    NAME        VARCHAR(16) NOT NULL,
    ROOM_NUMBER CHAR(2)     NOT NULL UNIQUE,
    BED_INFO    CHAR(2)     NOT NULL
);

CREATE TABLE GUEST
(
    GUEST_ID      SERIAL PRIMARY KEY,
    FIRST_NAME    VARCHAR(64),
    LAST_NAME     VARCHAR(64),
    EMAIL_ADDRESS VARCHAR(64),
    ADDRESS       VARCHAR(64),
    COUNTRY       VARCHAR(32),
    STATE         VARCHAR(12),
    PHONE_NUMBER  VARCHAR(24)
);

CREATE TABLE RESERVATION
(
    RESERVATION_ID SERIAL PRIMARY KEY,
    ROOM_ID        BIGINT NOT NULL,
    GUEST_ID       BIGINT NOT NULL,
    RES_DATE       DATE
);

ALTER TABLE RESERVATION
    ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID);
ALTER TABLE RESERVATION
    ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST (GUEST_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION (RES_DATE);

--User,Security,Role
CREATE TABLE security_role (
    id SERIAL PRIMARY KEY,
    description varchar(100) DEFAULT NULL,
    role_name varchar(100) DEFAULT NULL
);

CREATE TABLE security_user (
    id SERIAL PRIMARY KEY,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    first_name varchar(255) DEFAULT NULL,
    last_name varchar(255) NOT NULL
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT FK_SECURITY_USER_ID FOREIGN KEY (user_id) REFERENCES security_user (id),
    CONSTRAINT FK_SECURITY_ROLE_ID FOREIGN KEY (role_id) REFERENCES security_role (id)
);
